stages:
  - lint
  - build_packages
  - test_packages

code_lint:
  stage: lint
  image: registry.gitlab.com/opencv-ai/model-benchmark/lint:py375
  script:
    - cd $CI_PROJECT_DIR
    - python3.7 -V
    - echo ${CI_COMMIT_SHA}
    - SKIP=prettier pre-commit run -a
  artifacts:
    paths:
      - "*"
    exclude:
      - .cache
    expire_in: 1 day
    when: on_failure
  interruptible: true
  except:
    - main
    - develop
  tags:
    - lint

build_packages:
  stage: build_packages
  image: registry.gitlab.com/opencv-ai/model-benchmark/cpu:0.3
  script:
    - ./ci/build_packages.sh
  artifacts:
    paths:
      - "wheel_packages/"
    expose_as: "wheel_packages"
    expire_in: 1 week
    when: always
  tags:
    - build

test_models_gen2_develop_commit:
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
  stage: test_packages
  before_script:
    - cd $CI_PROJECT_DIR
    - python3.7 -m pip install modelplace-api[vis]@https://github.com/opencv-ai/modelplace-api/archive/v0.4.0.zip
    - python3.7 -m pip install depthai==0.0.2.1+87247bfb645027a30c68191d88fe1b69b70e39ac -f https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/depthai/
    - ./ci/install_packages.sh --no-deps
  script:
    - ./ci/run_test.sh
  after_script:
    - ./ci/uninstall_packages.sh
  tags:
    - oak
  except:
    - schedules
  allow_failure: true

test_models_gen2_develop_latest:
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
  stage: test_packages
  before_script:
    - cd $CI_PROJECT_DIR
    - python3.7 -m pip install modelplace-api[vis]@https://github.com/opencv-ai/modelplace-api/archive/v0.4.0.zip
    - python3.7 -m pip install -U --force-reinstall depthai@git+https://github.com/luxonis/depthai-python@gen2_develop
    - ./ci/install_packages.sh --no-deps
  script:
    - ci/run_test.sh
  after_script:
    - ./ci/uninstall_packages.sh
  tags:
    - oak
  except:
    - schedules
  allow_failure: true

test_models_gen2_develop_commit_schedule:
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
  stage: test_packages
  before_script:
    - cd $CI_PROJECT_DIR
    - ./ci/install_packages.sh
  script:
    - ci/run_test.sh
  after_script:
    - ./ci/uninstall_packages.sh
  tags:
    - oak
  only:
    - schedules
  allow_failure: true

test_models_gen2_develop_latest_schedule:
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
  stage: test_packages
  before_script:
    - cd $CI_PROJECT_DIR
    - ./ci/install_packages.sh
    - python3.7 -m pip install -U --force-reinstall depthai@git+https://github.com/luxonis/depthai-python@gen2_develop
  script:
    - ci/run_test.sh
  after_script:
    - ./ci/uninstall_packages.sh
  tags:
    - oak
  only:
    - schedules
  allow_failure: true
